# params.yaml
model:
  algorithm: "random_forest"  # Change this to 'random_forest' or 'svm' to use other models
  C: 1.0  # Regularization strength for Logistic Regression (not used for other models)
  max_iter: 100  # Maximum number of iterations for Logistic Regression (not used for other models)
  n_estimators: 100  # Number of trees for Random Forest (used only for RandomForest)
  max_depth: 10  # Maximum depth of trees for Random Forest (used only for RandomForest)
  kernel: "linear"  # Kernel type for SVM (used only for SVM)
  gamma: "scale"  # Gamma for SVM (used only for SVM)
  test_size: 0.3
